apiVersion: v1
kind: Service
metadata:
  name: {{ include "datametl.fullname" . }}-backend
  labels:
    {{- include "datametl.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "datametl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datametl.fullname" . }}-backend
  labels:
    {{- include "datametl.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "datametl.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "datametl.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "datametl.serviceAccountName" . }}
      {{- include "datametl.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.migrations.enabled }}
        {{- include "datametl.initWaitSchema" . | nindent 8 }}
        {{- else }}
        {{- include "datametl.initWaitDb" . | nindent 8 }}
        {{- end }}
      containers:
        - name: backend
          image: {{ include "datametl.image" (list . .Values.backend.repo .Values.backend.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            {{- include "datametl.appEnv" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
          {{- if .Values.backend.probes.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
