#!/usr/bin/env bash
#
# DataMETL one-line installer. Pulls the latest release's docker-compose.yml + .env.example,
# generates a Fernet encryption key, and starts the stack.
#
#   curl -fsSL https://github.com/sbcsp/datametl/releases/latest/download/install.sh | bash
#
# Or with a specific version + custom install dir:
#
#   DATAMETL_VERSION=v0.2.0 INSTALL_DIR=~/datametl bash <(curl ...)

set -euo pipefail

REPO="sbcsp/datametl"
RELEASE="${DATAMETL_VERSION:-latest}"
INSTALL_DIR="${INSTALL_DIR:-./datametl}"

bold()   { printf '\033[1m%s\033[0m\n' "$*"; }
info()   { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn()   { printf '\033[33m!\033[0m %s\n' "$*" >&2; }
err()    { printf '\033[31mERROR\033[0m %s\n' "$*" >&2; exit 1; }

# --- Pre-flight ---
command -v docker >/dev/null 2>&1 || err "Docker is required. Install Docker Desktop (macOS/Windows) or Docker Engine (Linux) first."
docker compose version >/dev/null 2>&1 || err "Docker Compose v2 plugin is required (\"docker compose\", not \"docker-compose\")."
command -v curl >/dev/null 2>&1 || err "curl is required."
command -v openssl >/dev/null 2>&1 || err "openssl is required (used to generate the Fernet encryption key)."

# --- Download ---
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

if [ "$RELEASE" = "latest" ]; then
  BASE="https://github.com/${REPO}/releases/latest/download"
else
  BASE="https://github.com/${REPO}/releases/download/${RELEASE}"
fi

info "Downloading from ${BASE}"
curl -fsSL "${BASE}/docker-compose.yml" -o docker-compose.yml \
  || err "Could not fetch docker-compose.yml. Is the release tag valid?"
# The release asset is `env.example` (no leading dot) because GitHub's release-download
# redirect 404s on dotfile names. We write it locally as `.env.example` so the rest of
# the script (cp to .env, sed to inject the key) is unchanged.
if ! curl -fsSL "${BASE}/env.example" -o .env.example 2>/dev/null; then
  # Fallback for old releases (pre-v0.2.4) that uploaded the asset as `.env.example`.
  curl -fsSL "${BASE}/.env.example" -o .env.example \
    || err "Could not fetch env.example."
fi

# Older releases sed-pinned the image tags to a specific version. Newer releases ship
# with the ${DATAMETL_VERSION:-latest} template intact. Normalize either way so that
# DATAMETL_VERSION in the user's .env always controls which images get pulled.
SED_INPLACE=(-i)
if [ "$(uname)" = "Darwin" ]; then
  SED_INPLACE=(-i '')
fi
sed "${SED_INPLACE[@]}" -E \
  -e 's|(ghcr\.io/sbcsp/datametl-(backend|frontend)):[^[:space:]"$]+|\1:${DATAMETL_VERSION:-latest}|g' \
  docker-compose.yml || true

# --- Generate Fernet key ---
# A Fernet key is 32 random bytes encoded as urlsafe base64. openssl produces standard
# base64; tr '+/' '-_' converts it to urlsafe form. The padding stays valid.
generate_key() {
  openssl rand -base64 32 | tr '+/' '-_'
}

# --- .env helpers ---
set_env() {
  # set_env KEY VALUE — portable in-place sed for .env
  local k="$1" v="$2"
  if [ "$(uname)" = "Darwin" ]; then
    sed -i '' "s|^${k}=.*|${k}=${v}|" .env
  else
    sed -i "s|^${k}=.*|${k}=${v}|" .env
  fi
}

generate_db_password() {
  openssl rand -hex 24
}

is_placeholder_key() {
  local key="$1"
  case "$key" in
    ""|CHANGE_ME|CHANGE_ME_GENERATE_A_FERNET_KEY|CHANGE_ME*) return 0 ;;
    *) return 1 ;;
  esac
}

is_weak_db_password() {
  local pw="$1"
  case "$pw" in
    ""|datametl|password|CHANGE_ME|CHANGE_ME_INSTALL_WILL_REPLACE|CHANGE_ME*) return 0 ;;
    *) return 1 ;;
  esac
}

# --- .env setup ---
if [ ! -f .env ]; then
  cp .env.example .env
  KEY="$(generate_key)"
  DBPASS="$(generate_db_password)"
  set_env ENCRYPTION_KEY "$KEY"
  set_env APP_DB_PASSWORD "$DBPASS"
  info "Generated .env with a fresh Fernet encryption key and strong APP_DB_PASSWORD."
else
  warn ".env already exists — keeping it. (Delete it and re-run if you want a fresh setup.)"
fi

# Refuse to start with an empty/placeholder ENCRYPTION_KEY (startup would fail anyway).
CURRENT_KEY="$(grep -E "^ENCRYPTION_KEY=" .env | head -1 | cut -d= -f2- || true)"
if is_placeholder_key "$CURRENT_KEY"; then
  err "ENCRYPTION_KEY in .env is empty or a placeholder. Set a real Fernet key (install.sh generates one on first run) before starting."
fi

# Upgrade weak default APP_DB_PASSWORD if still present (first-time or copied example).
CURRENT_DBPASS="$(grep -E "^APP_DB_PASSWORD=" .env | head -1 | cut -d= -f2- || true)"
if is_weak_db_password "$CURRENT_DBPASS"; then
  DBPASS="$(generate_db_password)"
  set_env APP_DB_PASSWORD "$DBPASS"
  info "Replaced weak/default APP_DB_PASSWORD with a strong random value."
fi

# --- Drop a Makefile so end users get the same `make`-based workflow as devs ---
# Lives next to docker-compose.yml; safe to delete or edit. Idempotently regenerated on
# re-install — we always overwrite so install.sh can ship new targets without leaving
# users on a stale local Makefile.
cat > Makefile <<'MAKEFILE'
# DataMETL — local management commands.
# Auto-generated by install.sh. Safe to edit; re-running install.sh will overwrite it.

COMPOSE := docker compose

.DEFAULT_GOAL := help
.PHONY: help up down restart pull update logs ps status

help:  ## Show this help
	@awk 'BEGIN{FS=":.*##"; printf "Usage: make <target>\n\nTargets:\n"} \
	  /^[a-zA-Z_-]+:.*##/{printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

up:        ## Start DataMETL (or apply docker-compose.yml changes)
	$(COMPOSE) up -d

down:      ## Stop DataMETL (containers removed; data persists in named volumes)
	$(COMPOSE) down

restart:   ## Restart all containers
	$(COMPOSE) restart

pull update:  ## Pull latest images from GHCR and restart
	$(COMPOSE) pull
	$(COMPOSE) up -d

logs:      ## Tail logs from all services
	$(COMPOSE) logs -f

ps status: ## Show container status
	$(COMPOSE) ps
MAKEFILE
info "Wrote Makefile (try \`make help\`)."

# --- Pull + start ---
info "Pulling images from ghcr.io/sbcsp..."
docker compose pull

info "Starting DataMETL..."
docker compose up -d

# Wait briefly for healthchecks to come up
sleep 3

# --- Done ---
PORT="$(grep '^FRONTEND_PORT=' .env | cut -d= -f2 || true)"
PORT="${PORT:-3000}"

echo ""
bold "DataMETL is up."
printf '  \033[36mFrontend\033[0m   http://localhost:%s\n' "$PORT"
printf '  \033[2mInstall dir\033[0m %s\n' "$(pwd)"
echo ""
echo "From the install dir ($(pwd)):"
echo "  Stop:    make down"
echo "  Update:  make update      (pulls latest images + restarts)"
echo "  Logs:    make logs"
echo "  Help:    make help        (full target list)"
echo ""
echo "Security:"
echo "  Put this deploy behind SSO (oauth2-proxy/Keycloak) OR set AUTH_ENABLED=true"
echo "  in .env with a strong AUTH_PASSWORD. /docs is disabled by default (DOCS_ENABLED)."
echo ""
